@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(followingSystem, "Following system") {
Container(followingService, "Following Service", "Java", "Handle and store user subscriptions", $tags="webApp")
ContainerDb(followingDatabase, "Following database", "PostgreSQL", "Stores user subscriptions",  $tags="db")
}
Container(postSystem, "Post system", "Software system", "Stores posts, generates personalized feeds of posts for users based on their subscriptions")

Rel(postSystem, followingService, "Gets subscribers of user")
Rel(followingService, followingDatabase, "Gets subscribers of user")

@enduml